name: MyDream
description: A new Flutter project.

version: 1.0.13+13

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

    
  cupertino_icons: ^1.0.2
  audioplayers: ^0.18.3
  in_app_purchase: 0.5.2
  provider: ^5.0.0
  sembast: ^3.0.2
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: false
  image_path_ios: resources/AppLogo/android/ic_launcher_xxxhdpi.png
  image_path_android: resources/AppLogo/android/ic_launcher_xxxhdpi.png
  adaptive_icon_background: resources/AppLogo/android/adaptiveBG.png
  adaptive_icon_foreground: resources/AppLogo/android/adaptiveFG.png

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
  - assets/